name: zoulingo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  flash_card: ^0.0.7
  get: ^4.6.5
  google_fonts: ^3.0.1
  device_preview: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_tts: 
  swipable_stack:
    git:
      url: https://github.com/Osama-creator/flutter_swipable_stack.git
      ref: develop        
  flutter_screenutil: ^5.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets: 
    - assets/images/
    - assets/audio/vater.m4a
    - assets/lang/ar.json
    - assets/lang/en.json

  uses-material-design: true
